# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('co_name', models.CharField(max_length=100)),
                ('co_link', models.TextField(default='none')),
                ('job_name', models.CharField(max_length=100)),
                ('co_type', models.CharField(default='none', max_length=20)),
                ('co_scale', models.CharField(default='none', max_length=20)),
                ('job_experience', models.CharField(default='none', max_length=20)),
                ('education', models.CharField(default='none', max_length=10)),
                ('salary', models.CharField(default='none', max_length=20)),
                ('duty', models.TextField(default='none')),
                ('scraping_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
    ]
