# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_jobs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scraping_date', models.DateTimeField(auto_now=True)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
